# vim: nospell

language: python
git:
  quiet: true
  submodules: false
branches:
  only:
    - /.*/
python:
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7-dev'

script:
  - black --check .
  - ./dl-vot --version
